image: node:20.18.0

clone:
  depth: full
pipelines:
  default:
    - step:
        script:
         # Configurar o usuário do Git
          - git config --global user.email "reinanappa0@gmail.com"
          - git config --global user.name "reinanSalesforce"
          - git push --mirror git@github.com:reinanSalesforce/RepositoryTeste.git