# Definição da imagem que vamos utilizar, nesse caso para React usamos o Node.js
image: node:20.18.0

pipelines:
  default:
    - step:
        name: Deploy to GitHub Pages
        script:
          # Instalar OpenSSL e SSH
          - apt-get update
          - apt-get install -y openssl ssh

          # Criar diretório .ssh se não existir
          - mkdir -p ~/.ssh

          # Adicionar a chave SSH privada
          - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

          # Definir permissões corretas para a chave
          - chmod 600 ~/.ssh/id_rsa

          # Adicionar GitHub ao known hosts (verificando a identidade do servidor)
          - ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Clonar o repositório GitHub Pages na branch main
          - git clone -b main git@github.com:FluxusTech0/TesteGithubPage.git

          # Mover para o diretório do repositório clonado
          - cd TesteGithubPage

          # Adicionar as configurações do usuário Git antes de qualquer commit
          - git config --global user.name "FluxusTech0"
          - git config --global user.email "projeto.businessAgil@gmail.com"

          # Adicionar as mudanças e fazer o commit
          - git add .
          - git commit -m 'Deploy automático pela pipeline'
          - git push origin main    

