image: node:20.18.0

clone:
  depth: full
pipelines:
  default:
    - step:
       script:
        - git config --global user.email "projeto.businessagil@gmail.com"
        - git config --global user.name "FluxusTech0"
        # Adicionar um reposit rio remoto chamado 'destination'
        - git remote add destination https://$GITHUB_TOKEN@github.com/FluxusTech0/LandingPage_Advocacia.git
        # Fazer o push para o 'destination'
        - git push destination --all
        - git push destination --tags