image: node:20.18.0

clone:
  depth: full
pipelines:
  default:
    - step:
       script:
        - git config --global user.email "reinanappa0@gmail.com"
        - git config --global user.name "reinanSalesforce"
        # Adicionar um reposit—rio remoto chamado 'destination'
        - git remote add destination git@github.com:reinanSalesforce/RepositoryTeste.git
        # Fazer o push para o 'destination'
        - git push destination --all
        - git push destination --tags

