# Definição da imagem que vamos utilizar, nesse caso para React usamos o Node.js
image: node:20.18.0

pipelines:
  default:
    - step:
        name: Build, Test and Deploy
        script:
          - echo "Running build and tests"
          - ./your-build-script.sh
          - echo $GIT_SSH_KEY > deploy_key
          - chmod 600 deploy_key
          - ssh-agent bash -c 'ssh-add deploy_key; git remote add github git@github.com:FluxusTech0/TesteGithubPage.git && git push github TesteGithubPage'
          
         